In [18]:
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Load the dataset
data = pd.read_pickle('../../data/processed/cleaned_articles.pkl')

In [19]:
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39863 entries, 0 to 39862
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              39863 non-null  object
 1   publisher          39863 non-null  object
 2   date               39863 non-null  object
 3   section            39863 non-null  object
 4   body               39863 non-null  object
 5   length             39863 non-null  int64
 6   letters_flag       39863 non-null  bool
 7   country_flag       39863 non-null  object
 8   foreign_countries  39863 non-null  object
 9   us_mentions        39863 non-null  object
 10  source_file        39863 non-null  object
 11  publisher_raw      39863 non-null  object
 12  section_clean      39845 non-null  object
 13  section_category   34176 non-null  object
dtypes: bool(1), int64(1), object(12)
memory usage: 4.0+ MB

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
0,A Well-Documented Childhood. A Very Private Life.,New York Times,2024-12-31,Section A; Column 0; National Desk; Pg. 16,Jimmy Carter's daughter had an extraordinary a...,1209,False,BOTH,"[Canada, Egypt, Mexico, Nicaragua]","[Massachusetts, Rhode Island, US, Washington]",NYT/1.DOCX,The New York Times,section a; column 0; national desk; pg. 16,US/National
1,These were the big stories in arts and culture...,Other publisher,2024-12-31,WHAT TO KNOW,The arts in Dayton continued to thrive in 2024...,3345,False,BOTH,"[France, Japan, Paris (Capital), Sierra Leone,...","[America, California, Florida, Georgia, Massac...",Other publishers/Files (500) (1).DOCX,Dayton Daily News (Ohio),what to know,None
2,She Exalted The Beauty Of Dance,New York Times,2024-12-31,Section C; Column 0; The Arts/Cultural Desk; P...,She was The New Yorker's first dance critic. H...,1314,False,BOTH,[Male (Capital)],"[New York, North Carolina, US, United States]",NYT/1.DOCX,The New York Times,section c; column 0; the arts/cultural desk; p...,Arts/Culture
3,"Under a Highway in Rio, a Dance Style Charms a...",New York Times,2024-12-31,WORLD; americas,"Trucks, buses and cars rumbled overhead, drown...",1333,False,BOTH,"[Brazil, Lima (Capital)]","[New York, US, United States]",NYT/1.DOCX,The New York Times,world; americas,World/International
4,"Congressional pay, minimum wage stagnant for y...",Other publisher,2024-12-31,OPINION; Pg. A13,ABSTRACT\nMembers of Congress have not seen a ...,921,False,US_ONLY,[],"[America, Delaware, Maryland, New Jersey, New ...",Other publishers/Files (500) (1).DOCX,The Philadelphia Inquirer,opinion; pg. a13,Opinion/Editorial/Letters

In [20]:
print(data.columns)

Index(['title', 'publisher', 'date', 'section', 'body', 'length',
       'letters_flag', 'country_flag', 'foreign_countries', 'us_mentions',
       'source_file', 'publisher_raw', 'section_clean', 'section_category'],
      dtype='object')

In [21]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()  
    # keep letters, space, -
    text = re.sub(r'[^a-z\-\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    words = text.split()

    # remove stop words
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]

    return ' '.join(words)

data['clean_text'] = data['body'].astype(str).apply(preprocess)

data[['body', 'clean_text']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/jingguo/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /Users/jingguo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,body,clean_text
0,Jimmy Carter's daughter had an extraordinary a...,jimmy carter daughter extraordinary well-docum...
1,The arts in Dayton continued to thrive in 2024...,art dayton continued thrive exciting debut new...
2,She was The New Yorker's first dance critic. H...,new yorker first dance critic wit could devast...
3,"Trucks, buses and cars rumbled overhead, drown...",truck bus car rumbled overhead drowning marcus...
4,ABSTRACT\nMembers of Congress have not seen a ...,abstract member congress seen pay raise since ...

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
    max_features=50000,     # Limit vocabulary size for efficiency
    ngram_range=(1, 2)      # include unigrams + bigramslike "small business" and "self employment"

)

# Vectorize the clean_text column
X = vectorizer.fit_transform(data['clean_text'])

# Extract vocabulary
vocab = vectorizer.get_feature_names_out()

print("Vocabulary size:", len(vocab))
vocab[:30]   # Show the first 30 vocabulary items

Vocabulary size: 50000

array(['aa', 'aaa', 'aaron', 'aarp', 'aback', 'abaire', 'abandon',
       'abandoned', 'abandoned building', 'abandoned house', 'abandoning',
       'abandonment', 'abatement', 'abbas', 'abbey', 'abbott',
       'abbreviated', 'abby', 'abc', 'abc news', 'abdel', 'abducted',
       'abduction', 'abdul', 'abdullah', 'abe', 'abel', 'aberration',
       'abetted', 'abhorrent'], dtype=object)

In [32]:
# Step 3: Define anchor words 
anchor_words_dict = {
    'Housing': [
        'housing', 'rent', 'tenant', 'affordable', 'homelessness',
        'landlord', 'eviction', 'apartment', 'mortgage'
    ],
    'Education': [
        'education', 'school', 'college', 'teacher', 'university', 'tuition',
        'student', 'curriculum', 'classroom', 'learning'
    ],
    'Union': [
        'union', 'labor', 'strike', 'worker', 'collective',
        'organizing', 'wage', 'bargaining', 'employment'
    ],
    'Election': [
        'election', 'vote', 'campaign', 'party', 'candidate', 'rally',
        'politics', 'ballot', 'primary', 'poll', 'democrat', 'republican'
    ],
    'Military': [
        'military', 'service', 'veteran', 'army', 'soldier',
        'defense', 'troop', 'combat', 'deployment', 'navy'
    ],
    'Indebtedness': [
        'debt', 'struggle', 'credit', 'bankrupt', 'bankruptcy',
        'loan', 'foreclosure', 'repayment', 'interest', 'borrower', 'default', 'financial'
    ],
    'Family': [
        'family', 'child', 'parent', 'marriage', 'spouse', 'household',
        'domestic', 'raising', 'sibling', 'divorce'
    ],
    'Art': [
        'book', 'review', 'theater', 'play', 'movie',
        'culture', 'novel', 'film', 'gallery', 'music', 'performance', 'exhibition', 'artist'
    ],
    'Health': [
        'overdose', 'patient', 'disease', 'treatment', 'mental', 'therapy',
        'nurse', 'clinic', 'pandemic', 'loneliness', 'medicine', 'doctor'
    ],
    'Business Ownership': [
        'business', 'entrepreneur', 'self employment',   
        'client', 'customer', 'firm', 'store', 'small business'   # bigram
    ],
    'Sports': [
        'soccer', 'hockey', 'athlete', 'league', 'tournament', 'game', 'score'
    ],
    'Religion': [
        'faith', 'minister', 'islamic', 'sermon', 'worship', 'belief'
    ]
}

topic_names = list(anchor_words_dict.keys())

# Map words to vocabulary indices
word_to_idx = {w: i for i, w in enumerate(vocab)}

anchor_indices = []
for topic, words in anchor_words_dict.items():
    idx_list = [word_to_idx[w] for w in words if w in word_to_idx]
    anchor_indices.append(idx_list)
    print(f"{topic}: {len(idx_list)} anchors found out of {len(words)} total")

Housing: 9 anchors found out of 9 total
Education: 10 anchors found out of 10 total
Union: 9 anchors found out of 9 total
Election: 12 anchors found out of 12 total
Military: 10 anchors found out of 10 total
Indebtedness: 12 anchors found out of 12 total
Family: 10 anchors found out of 10 total
Art: 13 anchors found out of 13 total
Health: 12 anchors found out of 12 total
Business Ownership: 7 anchors found out of 8 total
Sports: 7 anchors found out of 7 total
Religion: 6 anchors found out of 6 total

In [33]:
# Inspect which anchor words are missing from the vocabulary
missing_anchors = {}

for topic, words in anchor_words_dict.items():
    missing = [w for w in words if w not in word_to_idx]
    if missing:
        missing_anchors[topic] = missing

missing_anchors

{'Business Ownership': ['self employment']}

In [38]:
from corextopic import corextopic as ct

corex = ct.Corex(
    n_hidden=len(topic_names),
    seed=42,
)

corex.fit(X, words=vocab, anchors=anchor_indices)


print("Total correlation (TC) explained:", corex.tc)

Total correlation (TC) explained: 131.97892246781194

In [39]:
for i, topic in enumerate(corex.get_topics(n_words=15)):
    print(f"\n### Topic {i+1}: {topic_names[i]}")
    for word, score, idx in topic:
        print(f"{word:20} {score:.3f}")

### Topic 1: Housing
city                 0.133
housing              0.119
resident             0.113
neighborhood         0.113
building             0.101
apartment            0.086
developer            0.074
york city            0.073
mayor                0.073
community            0.072
property             0.071
brooklyn             0.068
park                 0.067
rent                 0.067
avenue               0.067

### Topic 2: Education
school               0.131
student              0.119
education            0.092
college              0.086
university           0.084
high school          0.082
black                0.064
racial               0.059
teacher              0.052
graduate             0.052
study                0.048
grade                0.047
high                 0.045
public school        0.044
professor            0.042

### Topic 3: Union
policy               0.158
economic             0.126
economy              0.112
state                0.084
government           0.081
health               0.081
wage                 0.078
country              0.072
time opinion         0.071
section facebook     0.068
opinion section      0.068
health care          0.064
administration       0.062
opinion              0.062
national             0.060

### Topic 4: Election
voter                0.388
democrat             0.335
republican           0.325
democratic           0.319
election             0.318
candidate            0.286
campaign             0.278
vote                 0.234
presidential         0.225
party                0.199
trump                0.186
poll                 0.185
political            0.157
senator              0.156
president            0.154

### Topic 5: Military
said                 0.146
official             0.092
month                0.081
former               0.080
said mr              0.078
leader               0.078
mr                   0.076
week                 0.070
last                 0.070
would                0.065
office               0.065
law                  0.059
saying               0.057
interview            0.056
told                 0.055

### Topic 6: Indebtedness
income               0.143
tax                  0.114
percent              0.111
cost                 0.105
pay                  0.104
rate                 0.099
billion              0.098
million              0.096
increase             0.096
federal              0.083
plan                 0.073
higher               0.071
money                0.070
financial            0.069
low                  0.069

### Topic 7: Family
friend               0.084
never                0.083
know                 0.082
got                  0.082
thing                0.081
life                 0.079
something            0.074
mother               0.073
always               0.073
wanted               0.070
father               0.069
go                   0.069
went                 0.069
thought              0.068
knew                 0.066

### Topic 8: Art
film                 0.181
character            0.161
movie                0.138
actor                0.107
music                0.105
theater              0.102
star                 0.099
comedy               0.095
story                0.094
scene                0.092
love                 0.092
drama                0.084
play                 0.082
novel                0.082
directed             0.074

### Topic 9: Health
photograph           0.095
york time            0.087
new york             0.083
york                 0.083
even                 0.077
like                 0.069
often                0.066
way                  0.066
much                 0.061
article              0.059
photo                0.058
yet                  0.057
right                0.056
sense                0.056
new                  0.055

### Topic 10: Business Ownership
street               0.097
home                 0.086
nearby               0.080
shop                 0.076
foot                 0.073
area                 0.072
restaurant           0.071
near                 0.070
store                0.069
block                0.068
mile                 0.067
place                0.065
built                0.064
floor                0.063
window               0.063

### Topic 11: Sports
art                  0.088
museum               0.062
world                0.060
th                   0.055
style                0.048
eye                  0.045
century              0.045
night                0.045
th century           0.045
light                0.043
glass                0.042
collection           0.041
game                 0.041
painting             0.040
club                 0.040

### Topic 12: Religion
minister             0.107
prime minister       0.094
europe               0.079
european             0.067
france               0.065
parliament           0.064
war                  0.058
prime                0.058
foreign              0.053
united               0.053
communist            0.052
power                0.052
united state         0.049
britain              0.042
democracy            0.040

In [43]:
from corextopic import corextopic as ct

# Create a new Corex model (no anchor_strength here)
corex2 = ct.Corex(
    n_hidden=len(topic_names),
    seed=42
)

# Fit with anchors and a stronger anchor_strength
corex2.fit(
    X,
    words=vocab,
    anchors=anchor_indices,
    anchor_strength=3 
)

print("TC:", corex2.tc)

TC: 140.78105863187363

In [44]:
for i, topic in enumerate(corex2.get_topics(n_words=15)):
    print(f"\n### Topic {i+1}: {topic_names[i]}")
    for word, score, idx in topic:
        print(f"{word:20} {score:.3f}")

### Topic 1: Housing
housing              0.425
apartment            0.297
rent                 0.242
tenant               0.186
affordable           0.149
city                 0.126
landlord             0.117
resident             0.111
neighborhood         0.109
building             0.099
developer            0.074
community            0.072
property             0.071
york city            0.069
development          0.068

### Topic 2: Education
school               0.631
student              0.519
college              0.362
education            0.354
university           0.341
teacher              0.236
classroom            0.130
high school          0.114
tuition              0.101
learning             0.086
curriculum           0.075
graduate             0.061
high                 0.057
grade                0.053
public school        0.050

### Topic 3: Union
wage                 0.315
worker               0.254
labor                0.230
union                0.202
policy               0.146
economic             0.130
economy              0.114
employment           0.079
state                0.077
health               0.076
time opinion         0.074
section facebook     0.071
opinion section      0.070
country              0.068
health care          0.061

### Topic 4: Election
democrat             1.043
election             1.025
republican           1.001
candidate            0.905
campaign             0.878
vote                 0.752
party                0.629
poll                 0.586
politics             0.435
voter                0.397
primary              0.392
democratic           0.324
ballot               0.237
presidential         0.227
rally                0.198

### Topic 5: Military
said                 0.139
official             0.091
former               0.080
leader               0.079
month                0.079
said mr              0.074
military             0.072
mr                   0.071
week                 0.069
defense              0.069
last                 0.067
office               0.065
service              0.064
would                0.062
law                  0.062

### Topic 6: Indebtedness
financial            0.234
income               0.142
debt                 0.128
loan                 0.127
tax                  0.115
percent              0.110
credit               0.109
interest             0.108
cost                 0.104
pay                  0.103
rate                 0.099
billion              0.097
increase             0.094
million              0.094
federal              0.083

### Topic 7: Family
child                0.187
family               0.154
parent               0.153
friend               0.086
life                 0.085
never                0.083
know                 0.080
mother               0.080
thing                0.080
got                  0.078
father               0.074
always               0.072
something            0.071
wanted               0.069
go                   0.067

### Topic 8: Art
film                 0.574
movie                0.430
music                0.336
theater              0.335
artist               0.268
novel                0.254
play                 0.243
performance          0.190
book                 0.189
character            0.155
actor                0.105
review               0.099
art                  0.098
scene                0.096
star                 0.095

### Topic 9: Health
photograph           0.102
york time            0.091
new york             0.085
york                 0.084
even                 0.080
pandemic             0.074
like                 0.068
often                0.065
way                  0.064
much                 0.061
article              0.060
photo                0.059
right                0.058
yet                  0.057
left                 0.057

### Topic 10: Business Ownership
store                0.240
business             0.122
customer             0.108
street               0.096
shop                 0.081
home                 0.081
nearby               0.078
restaurant           0.074
foot                 0.072
area                 0.070
near                 0.068
block                0.067
park                 0.066
built                0.064
place                0.064

### Topic 11: Sports
game                 0.179
league               0.063
room                 0.059
world                0.056
night                0.050
fan                  0.047
best                 0.045
eye                  0.045
style                0.045
th                   0.045
player               0.044
club                 0.044
athlete              0.044
soccer               0.043
season               0.041

### Topic 12: Religion
minister             0.361
prime minister       0.099
islamic              0.082
government           0.082
europe               0.076
european             0.066
parliament           0.065
france               0.062
prime                0.061
war                  0.058
united               0.053
foreign              0.052
power                0.052
communist            0.051
united state         0.049