In [1]:
import pandas as pd

# Load the dataset
data = pd.read_pickle('../../data/processed/cleaned_articles.pkl')

In [2]:
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39863 entries, 0 to 39862
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              39863 non-null  object
 1   publisher          39863 non-null  object
 2   date               39863 non-null  object
 3   section            39863 non-null  object
 4   body               39863 non-null  object
 5   length             39863 non-null  int64
 6   letters_flag       39863 non-null  bool
 7   country_flag       39863 non-null  object
 8   foreign_countries  39863 non-null  object
 9   us_mentions        39863 non-null  object
 10  source_file        39863 non-null  object
 11  publisher_raw      39863 non-null  object
 12  section_clean      39845 non-null  object
 13  section_category   34176 non-null  object
dtypes: bool(1), int64(1), object(12)
memory usage: 4.0+ MB

,title,publisher,date,section,body,length,letters_flag,country_flag,foreign_countries,us_mentions,source_file,publisher_raw,section_clean,section_category
0,A Well-Documented Childhood. A Very Private Life.,New York Times,2024-12-31,Section A; Column 0; National Desk; Pg. 16,Jimmy Carter's daughter had an extraordinary a...,1209,False,BOTH,"[Canada, Egypt, Mexico, Nicaragua]","[Massachusetts, Rhode Island, US, Washington]",NYT/1.DOCX,The New York Times,section a; column 0; national desk; pg. 16,US/National
1,These were the big stories in arts and culture...,Other publisher,2024-12-31,WHAT TO KNOW,The arts in Dayton continued to thrive in 2024...,3345,False,BOTH,"[France, Japan, Paris (Capital), Sierra Leone,...","[America, California, Florida, Georgia, Massac...",Other publishers/Files (500) (1).DOCX,Dayton Daily News (Ohio),what to know,None
2,She Exalted The Beauty Of Dance,New York Times,2024-12-31,Section C; Column 0; The Arts/Cultural Desk; P...,She was The New Yorker's first dance critic. H...,1314,False,BOTH,[Male (Capital)],"[New York, North Carolina, US, United States]",NYT/1.DOCX,The New York Times,section c; column 0; the arts/cultural desk; p...,Arts/Culture
3,"Under a Highway in Rio, a Dance Style Charms a...",New York Times,2024-12-31,WORLD; americas,"Trucks, buses and cars rumbled overhead, drown...",1333,False,BOTH,"[Brazil, Lima (Capital)]","[New York, US, United States]",NYT/1.DOCX,The New York Times,world; americas,World/International
4,"Congressional pay, minimum wage stagnant for y...",Other publisher,2024-12-31,OPINION; Pg. A13,ABSTRACT\nMembers of Congress have not seen a ...,921,False,US_ONLY,[],"[America, Delaware, Maryland, New Jersey, New ...",Other publishers/Files (500) (1).DOCX,The Philadelphia Inquirer,opinion; pg. a13,Opinion/Editorial/Letters

In [3]:
print(data.columns)

Index(['title', 'publisher', 'date', 'section', 'body', 'length',
       'letters_flag', 'country_flag', 'foreign_countries', 'us_mentions',
       'source_file', 'publisher_raw', 'section_clean', 'section_category'],
      dtype='object')

### Preprocess with custom stopwords

In [4]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# ---- 1. Define custom stopwords ----
custom_stopwords = {
    'said', 'say', 'saying', 'told',
    'mr', 'ms', 'mrs',
    'report', 'reported', 'interview', 'according',
    'article', 'photo', 'photograph', 'graphic',
    'someone', 'anyone', 'everyone', 'everybody',
    'york', 'new', 'time'
}

# ---- 2. Merge with NLTK stopwords ----
stop_words = set(stopwords.words('english')).union(custom_stopwords)

# ---- 3. Lemmatizer ----
lemmatizer = WordNetLemmatizer()

# ---- 4. Preprocess function ----
def preprocess(text):
    text = text.lower()  
    text = re.sub(r'[^a-z\s]', ' ', text)   # keep letters, spaces
    text = re.sub(r'\s+', ' ', text).strip()

    words = text.split()
    words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]

    return ' '.join(words)

# ---- 5. Apply cleaning ----
data['clean_text'] = data['body'].astype(str).apply(preprocess)

data[['body', 'clean_text']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/jingguo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/jingguo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,body,clean_text
0,Jimmy Carter's daughter had an extraordinary a...,jimmy carter daughter extraordinary well docum...
1,The arts in Dayton continued to thrive in 2024...,art dayton continued thrive exciting debut art...
2,She was The New Yorker's first dance critic. H...,yorker first dance critic wit could devastatin...
3,"Trucks, buses and cars rumbled overhead, drown...",truck bus car rumbled overhead drowning marcus...
4,ABSTRACT\nMembers of Congress have not seen a ...,abstract member congress seen pay raise since ...

### Vectorize (CountVectorizer)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
    max_features=50000,     # Limit vocabulary size for efficiency
    ngram_range=(1, 2)      # include unigrams + bigramslike "small business" and "self employment"

)

# Vectorize the clean_text column
X = vectorizer.fit_transform(data['clean_text'])

# Extract vocabulary
vocab = vectorizer.get_feature_names_out()

print("Vocabulary size:", len(vocab))
vocab[:30]   # Show the first 30 vocabulary items

Vocabulary size: 50000

array(['aa', 'aaa', 'aaron', 'aarp', 'aback', 'abaire', 'abandon',
       'abandoned', 'abandoned building', 'abandoned home',
       'abandoned house', 'abandoning', 'abandonment', 'abatement',
       'abbas', 'abbey', 'abbott', 'abbreviated', 'abby', 'abc',
       'abc news', 'abdel', 'abducted', 'abduction', 'abdul', 'abdullah',
       'abe', 'abel', 'aberration', 'abetted'], dtype=object)

### Define anchors + build anchor_indices + missing_anchors

In [6]:
# Step 3: Define anchor words 
anchor_words_dict = {
    'Housing': [
        'housing', 'rent', 'tenant', 'affordable', 'homelessness',
        'landlord', 'eviction', 'apartment', 'mortgage'
    ],
    'Education': [
        'education', 'school', 'college', 'teacher', 'university', 'tuition',
        'student', 'curriculum', 'classroom', 'learning'
    ],
    'Union': [
        'union', 'labor', 'strike', 'worker', 'collective',
        'organizing', 'wage', 'bargaining', 'employment'
    ],
    'Election': [
        'election', 'vote', 'campaign', 'party', 'candidate', 'rally',
        'politics', 'ballot', 'primary', 'poll', 'democrat', 'republican'
    ],
    'Military': [
        'military', 'service', 'veteran', 'army', 'soldier',
        'defense', 'troop', 'combat', 'deployment', 'navy'
    ],
    'Indebtedness': [
        'debt', 'struggle', 'credit', 'bankrupt', 'bankruptcy',
        'loan', 'foreclosure', 'repayment', 'interest', 'borrower', 'default', 'financial'
    ],
    'Family': [
        'family', 'child', 'parent', 'marriage', 'spouse', 'household',
        'domestic', 'raising', 'sibling', 'divorce'
    ],
    'Art': [
        'book', 'review', 'theater', 'play', 'movie',
        'culture', 'novel', 'film', 'gallery', 'music', 'performance', 'exhibition', 'artist'
    ],
    'Health': [
        'overdose', 'patient', 'disease', 'treatment', 'mental', 'therapy',
        'nurse', 'clinic', 'pandemic', 'loneliness', 'medicine', 'doctor'
    ],
    'Business Ownership': [
        'business', 'entrepreneur', 'self employment',   
        'client', 'customer', 'firm', 'store', 'small business'   # bigram
    ],
    'Sports': [
        'soccer', 'hockey', 'athlete', 'league', 'tournament', 'game', 'score'
    ],
    'Religion': [
        'faith', 'minister', 'islamic', 'sermon', 'worship', 'belief'
    ]
}

topic_names = list(anchor_words_dict.keys())

# Map words to vocabulary indices
word_to_idx = {w: i for i, w in enumerate(vocab)}

anchor_indices = []
for topic, words in anchor_words_dict.items():
    idx_list = [word_to_idx[w] for w in words if w in word_to_idx]
    anchor_indices.append(idx_list)
    print(f"{topic}: {len(idx_list)} anchors found out of {len(words)} total")

Housing: 9 anchors found out of 9 total
Education: 10 anchors found out of 10 total
Union: 9 anchors found out of 9 total
Election: 12 anchors found out of 12 total
Military: 10 anchors found out of 10 total
Indebtedness: 12 anchors found out of 12 total
Family: 10 anchors found out of 10 total
Art: 13 anchors found out of 13 total
Health: 12 anchors found out of 12 total
Business Ownership: 7 anchors found out of 8 total
Sports: 7 anchors found out of 7 total
Religion: 6 anchors found out of 6 total

In [7]:
# Inspect which anchor words are missing from the vocabulary
missing_anchors = {}

for topic, words in anchor_words_dict.items():
    missing = [w for w in words if w not in word_to_idx]
    if missing:
        missing_anchors[topic] = missing

missing_anchors

{'Business Ownership': ['self employment']}

### Train corex (strength=1) + print topics

In [15]:
from corextopic import corextopic as ct

corex = ct.Corex(
    n_hidden=len(topic_names),
    seed=42,
)

corex.fit(X, words=vocab, anchors=anchor_indices)


print("Total correlation (TC) explained:", corex.tc)

Total correlation (TC) explained: 129.740758276483

In [9]:
for i, topic in enumerate(corex.get_topics(n_words=15)):
    print(f"\n### Topic {i+1}: {topic_names[i]}")
    for word, score, idx in topic:
        print(f"{word:20} {score:.3f}")

### Topic 1: Housing
city                 0.133
housing              0.124
resident             0.119
neighborhood         0.118
building             0.106
apartment            0.086
community            0.077
developer            0.074
property             0.073
mayor                0.073
area                 0.071
rent                 0.070
development          0.068
park                 0.067
real estate          0.066

### Topic 2: Education
school               0.130
student              0.119
education            0.092
college              0.084
university           0.081
high school          0.081
black                0.063
racial               0.058
teacher              0.052
graduate             0.051
grade                0.048
study                0.047
public school        0.045
high                 0.044
academic             0.041

### Topic 3: Union
policy               0.112
economic             0.087
time                 0.077
country              0.073
time opinion         0.072
many                 0.069
section facebook     0.069
opinion section      0.068
opinion              0.067
even                 0.066
change               0.063
facebook             0.063
follow time          0.061
likely               0.061
le                   0.060

### Topic 4: Election
voter                0.386
democrat             0.337
republican           0.332
democratic           0.318
election             0.317
candidate            0.283
campaign             0.278
vote                 0.232
presidential         0.225
party                0.197
trump                0.194
poll                 0.183
donald trump         0.160
president            0.158
political            0.157

### Topic 5: Military
official             0.079
law                  0.077
police               0.070
court                0.063
month                0.060
office               0.054
week                 0.053
case                 0.052
public               0.051
officer              0.049
last                 0.048
attack               0.047
member               0.045
accused              0.045
justice              0.044

### Topic 6: Indebtedness
income               0.142
tax                  0.123
percent              0.114
pay                  0.102
cost                 0.102
billion              0.100
rate                 0.099
increase             0.097
million              0.094
federal              0.086
benefit              0.076
economy              0.076
higher               0.073
plan                 0.073
financial            0.067

### Topic 7: Family
know                 0.083
never                0.083
got                  0.082
thing                0.081
friend               0.081
life                 0.077
something            0.074
always               0.071
go                   0.070
mother               0.070
wanted               0.069
went                 0.068
thought              0.068
get                  0.066
really               0.066

### Topic 8: Art
film                 0.197
movie                0.148
character            0.144
music                0.118
theater              0.117
actor                0.114
star                 0.102
comedy               0.102
art                  0.098
scene                0.095
artist               0.088
drama                0.087
play                 0.084
love                 0.082
directed             0.078

### Topic 9: Health
world                0.082
self                 0.076
author               0.060
sense                0.059
writing              0.055
man                  0.055
writer               0.054
woman                0.052
century              0.051
word                 0.051
read                 0.050
wrote                0.049
pp                   0.048
writes               0.048
moment               0.048

### Topic 10: Business Ownership
street               0.092
photo                0.084
restaurant           0.082
shop                 0.075
photograph           0.074
home                 0.074
foot                 0.072
nearby               0.072
room                 0.067
place                0.066
near                 0.065
floor                0.065
store                0.064
space                0.064
window               0.061

### Topic 11: Sports
game                 0.060
fan                  0.056
night                0.055
best                 0.050
player               0.049
sport                0.047
club                 0.047
season               0.047
eye                  0.047
boy                  0.047
playing              0.046
team                 0.044
style                0.042
big                  0.036
name                 0.035

### Topic 12: Religion
minister             0.109
prime minister       0.096
government           0.082
europe               0.081
european             0.071
france               0.067
parliament           0.065
prime                0.059
foreign              0.055
war                  0.053
united               0.053
communist            0.052
united state         0.049
power                0.049
britain              0.042

### Train corex2 (strength=3) + print topic

In [10]:
from corextopic import corextopic as ct

# Create a new Corex model
corex2 = ct.Corex(
    n_hidden=len(topic_names),
    seed=42
)

# Fit with anchors and a stronger anchor_strength
corex2.fit(
    X,
    words=vocab,
    anchors=anchor_indices,
    anchor_strength=3 
)

print("TC:", corex2.tc)

TC: 138.3638517230551

In [11]:
for i, topic in enumerate(corex2.get_topics(n_words=15)):
    print(f"\n### Topic {i+1}: {topic_names[i]}")
    for word, score, idx in topic:
        print(f"{word:20} {score:.3f}")

### Topic 1: Housing
housing              0.435
apartment            0.294
rent                 0.245
tenant               0.188
affordable           0.149
city                 0.126
landlord             0.118
resident             0.116
neighborhood         0.115
building             0.104
developer            0.076
community            0.075
property             0.073
development          0.070
area                 0.070

### Topic 2: Education
school               0.675
student              0.542
college              0.372
education            0.358
university           0.322
teacher              0.254
classroom            0.133
high school          0.120
tuition              0.103
learning             0.089
curriculum           0.079
graduate             0.062
high                 0.058
grade                0.055
public school        0.052

### Topic 3: Union
wage                 0.172
worker               0.150
labor                0.139
policy               0.130
union                0.125
economic             0.107
economy              0.085
state                0.081
country              0.076
time opinion         0.070
section facebook     0.066
many                 0.066
opinion section      0.066
time                 0.065
opinion              0.064

### Topic 4: Election
democrat             1.050
election             1.025
republican           1.014
candidate            0.900
campaign             0.874
vote                 0.752
party                0.627
poll                 0.582
politics             0.441
voter                0.399
primary              0.392
democratic           0.322
ballot               0.239
presidential         0.226
rally                0.195

### Topic 5: Military
military             0.103
defense              0.093
official             0.076
law                  0.075
police               0.071
court                0.062
service              0.061
army                 0.059
month                0.057
office               0.052
week                 0.051
case                 0.051
officer              0.050
public               0.049
attack               0.048

### Topic 6: Indebtedness
financial            0.232
income               0.138
debt                 0.127
loan                 0.125
tax                  0.119
percent              0.109
interest             0.109
credit               0.107
pay                  0.104
cost                 0.104
billion              0.100
rate                 0.098
increase             0.095
million              0.095
federal              0.084

### Topic 7: Family
child                0.187
family               0.157
parent               0.146
never                0.081
friend               0.081
life                 0.081
know                 0.079
got                  0.079
thing                0.079
mother               0.074
go                   0.071
something            0.071
always               0.069
father               0.067
went                 0.067

### Topic 8: Art
film                 0.606
movie                0.458
music                0.362
theater              0.358
artist               0.288
play                 0.253
novel                0.212
performance          0.201
character            0.150
book                 0.137
actor                0.109
art                  0.104
star                 0.099
gallery              0.096
scene                0.096

### Topic 9: Health
world                0.079
self                 0.077
author               0.062
sense                0.060
century              0.055
woman                0.054
often                0.053
wrote                0.051
history              0.051
word                 0.049
writing              0.049
writes               0.049
read                 0.047
moment               0.046
society              0.046

### Topic 10: Business Ownership
store                0.216
customer             0.096
business             0.095
street               0.091
photo                0.083
restaurant           0.082
shop                 0.078
photograph           0.073
home                 0.072
foot                 0.071
nearby               0.071
room                 0.066
space                0.065
place                0.065
floor                0.064

### Topic 11: Sports
game                 0.230
league               0.085
fan                  0.059
athlete              0.058
player               0.055
night                0.054
sport                0.054
soccer               0.052
best                 0.051
season               0.051
team                 0.051
played               0.051
tournament           0.049
playing              0.049
club                 0.048

### Topic 12: Religion
minister             0.376
prime minister       0.107
islamic              0.086
europe               0.080
government           0.075
european             0.070
france               0.069
parliament           0.066
prime                0.064
foreign              0.052
communist            0.051
united               0.050
war                  0.049
united state         0.046
power                0.046

### Train corex2 (strength=5) + print topic

In [13]:
from corextopic import corextopic as ct

corex5 = ct.Corex(
    n_hidden=len(topic_names),
    seed=42
)

corex5.fit(
    X,
    words=vocab,
    anchors=anchor_indices,
    anchor_strength=5
)

print("Total correlation (TC):", corex5.tc)

Total correlation (TC): 148.44585760702984

In [14]:
n_words = 15  

for i, topic in enumerate(corex5.get_topics(n_words=n_words)):
    print(f"\n### Topic {i+1}: {topic_names[i]}")
    for word, score, idx in topic:
        print(f"{word:20} {score:.3f}")

### Topic 1: Housing
housing              0.847
apartment            0.555
rent                 0.465
tenant               0.340
affordable           0.286
landlord             0.227
city                 0.118
mortgage             0.111
neighborhood         0.109
resident             0.109
building             0.099
eviction             0.084
developer            0.075
community            0.073
property             0.071

### Topic 2: Education
school               1.330
student              1.048
college              0.744
education            0.653
university           0.598
teacher              0.489
classroom            0.229
tuition              0.195
learning             0.147
curriculum           0.132
high school          0.127
graduate             0.060
high                 0.057
public school        0.052
grade                0.050

### Topic 3: Union
wage                 0.895
labor                0.887
worker               0.788
union                0.663
employment           0.192
strike               0.112
bargaining           0.097
section facebook     0.085
time opinion         0.082
opinion section      0.082
economic             0.080
follow time          0.072
organizing           0.068
twitter nytopinion   0.065
nytopinion           0.065

### Topic 4: Election
democrat             1.791
election             1.772
republican           1.737
candidate            1.511
campaign             1.480
vote                 1.313
party                1.082
poll                 0.986
politics             0.761
primary              0.654
ballot               0.405
voter                0.400
rally                0.334
democratic           0.325
presidential         0.224

### Topic 5: Military
military             0.258
defense              0.198
army                 0.148
service              0.119
troop                0.116
veteran              0.087
combat               0.085
soldier              0.084
official             0.074
law                  0.073
police               0.072
court                0.062
officer              0.054
month                0.051
office               0.050

### Topic 6: Indebtedness
financial            0.426
debt                 0.243
loan                 0.223
interest             0.199
credit               0.185
income               0.137
tax                  0.121
percent              0.115
cost                 0.101
rate                 0.100
billion              0.097
pay                  0.095
increase             0.094
million              0.093
federal              0.087

### Topic 7: Family
child                0.418
parent               0.334
family               0.328
marriage             0.128
life                 0.095
mother               0.089
friend               0.085
never                0.083
father               0.080
know                 0.075
thing                0.073
always               0.071
something            0.068
got                  0.068
sibling              0.066

### Topic 8: Art
film                 0.977
movie                0.732
theater              0.583
music                0.578
artist               0.480
novel                0.448
play                 0.405
book                 0.352
performance          0.324
review               0.175
gallery              0.160
exhibition           0.157
character            0.153
culture              0.147
art                  0.105

### Topic 9: Health
pandemic             0.205
time                 0.084
even                 0.079
many                 0.070
much                 0.063
right                0.062
le                   0.061
way                  0.059
treatment            0.058
often                0.057
point                0.057
white                0.056
social               0.056
american             0.055
among                0.055

### Topic 10: Business Ownership
store                0.418
business             0.206
customer             0.205
street               0.090
restaurant           0.084
shop                 0.082
photo                0.078
home                 0.072
foot                 0.070
nearby               0.070
photograph           0.068
place                0.064
near                 0.063
room                 0.063
space                0.063

### Topic 11: Sports
game                 0.424
league               0.152
athlete              0.109
soccer               0.100
tournament           0.085
hockey               0.066
score                0.061
fan                  0.057
world                0.056
player               0.054
night                0.054
sport                0.053
best                 0.051
team                 0.050
played               0.049

### Topic 12: Religion
minister             0.690
islamic              0.159
prime minister       0.107
europe               0.077
faith                0.072
european             0.068
parliament           0.065
france               0.063
prime                0.063
belief               0.063
country              0.062
war                  0.054
united               0.052
foreign              0.052
power                0.050